export interface SeedItem {
  name: string
  type: string
  color: string
  material: string
  season: string
  occasions: string[]
  brand: string
  price: string
  priceValue: number
  image: string
  searchQuery: string
}

export const SEED_WARDROBE: SeedItem[] = [
  // TOPS
  { name: 'Paint Drip Trucker Hat', type: 'accessory', color: 'Black', material: 'Cotton/Mesh', season: 'all', occasions: ['casual', 'streetwear'], brand: 'AMIRI', price: '£295', priceValue: 295, image: '/api/proxy-image?url=https://cdn-images.farfetch-contents.com/17/63/76/24/17637624_37069583_1000.jpg', searchQuery: 'AMIRI paint drip trucker hat black' },
  { name: 'Compass Patch T-Shirt', type: 'top', color: 'White', material: '100% Cotton', season: 'summer', occasions: ['casual', 'streetwear'], brand: 'Stone Island', price: '£165', priceValue: 165, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R04211610_WHITE_M?wid=800', searchQuery: 'Stone Island compass patch t-shirt white' },
  { name: 'Essentials Tee', type: 'top', color: 'Cream', material: '100% Cotton', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Fear of God', price: '£90', priceValue: 90, image: '/api/proxy-image?url=https://images.stockx.com/images/Fear-of-God-Essentials-Tee-Cream.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90', searchQuery: 'Fear of God Essentials cream t-shirt' },
  { name: 'Polo Bear Knit Sweater', type: 'top', color: 'Navy', material: 'Cotton Blend', season: 'autumn', occasions: ['smart casual', 'casual'], brand: 'Ralph Lauren', price: '£329', priceValue: 329, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R03985863_NAVY_M?wid=800', searchQuery: 'Ralph Lauren polo bear navy sweater' },
  { name: 'Box Logo Tee', type: 'top', color: 'Red', material: '100% Cotton', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Supreme', price: '£148', priceValue: 148, image: '/api/proxy-image?url=https://images.stockx.com/images/Supreme-Box-Logo-Tee-Red.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90', searchQuery: 'Supreme box logo tee red' },
  { name: 'Club Fleece Hoodie', type: 'top', color: 'Black', material: 'Cotton Fleece', season: 'autumn', occasions: ['casual', 'sport'], brand: 'Nike', price: '£59.99', priceValue: 59.99, image: '/api/proxy-image?url=https://static.nike.com/a/images/t_prod_ss/w_640,c_limit,f_auto/09cfc26c-8c07-4783-a4c8-1d4e87e0d68a/sportswear-club-fleece-pullover-hoodie.png', searchQuery: 'Nike club fleece hoodie black' },
  { name: 'Trefoil Crew Sweatshirt', type: 'top', color: 'Grey Heather', material: 'French Terry', season: 'autumn', occasions: ['casual', 'sport'], brand: 'adidas Originals', price: '£55', priceValue: 55, image: '/api/proxy-image?url=https://assets.adidas.com/images/w_600,f_auto,q_auto/fd0a27cc2c724daba3b9ae8c01391064_9366/Trefoil_Crew_Sweatshirt_Grey_HE2069_01_laydown.jpg', searchQuery: 'adidas originals trefoil crew sweatshirt grey' },
  { name: 'G9 Harrington Jacket', type: 'outerwear', color: 'Tan', material: 'Cotton', season: 'spring', occasions: ['smart casual', 'casual'], brand: 'Baracuta', price: '£395', priceValue: 395, image: '/api/proxy-image?url=https://www.baracuta.com/on/demandware.static/-/Sites-WPBARACUTA-Library/default/dw7e2d2c46/images/pdp/G9/G9-Classic-Tan-1.jpg', searchQuery: 'Baracuta G9 harrington jacket tan' },
  { name: '1996 Retro Nuptse Jacket', type: 'outerwear', color: 'Black', material: 'Nylon/700 Fill Down', season: 'winter', occasions: ['casual', 'streetwear'], brand: 'The North Face', price: '£290', priceValue: 290, image: '/api/proxy-image?url=https://images.thenorthface.com/is/image/TheNorthFace/NF0A3C8D_JK3_hero?wid=780&hei=906', searchQuery: 'North Face 1996 retro nuptse jacket black' },
  { name: 'Wool Blend Overcoat', type: 'outerwear', color: 'Camel', material: 'Wool Blend', season: 'winter', occasions: ['smart', 'formal'], brand: 'COS', price: '£175', priceValue: 175, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R04126543_CAMEL_M?wid=800', searchQuery: 'COS camel wool overcoat' },
  // BOTTOMS
  { name: '501 Original Fit Jeans', type: 'bottom', color: 'Indigo', material: '100% Cotton Denim', season: 'all', occasions: ['casual'], brand: "Levi's", price: '£95', priceValue: 95, image: '/api/proxy-image?url=https://lsco.scene7.com/is/image/lsco/005010101-front-pdp?fmt=jpeg&qlt=70&resMode=bisharp&fit=crop,0&op_usm=1.25,0.6,8&wid=800&hei=800', searchQuery: "Levi's 501 original fit jeans indigo" },
  { name: 'Tech Fleece Joggers', type: 'bottom', color: 'Black', material: 'Tech Fleece', season: 'all', occasions: ['casual', 'sport'], brand: 'Nike', price: '£89.99', priceValue: 89.99, image: '/api/proxy-image?url=https://static.nike.com/a/images/t_prod_ss/w_640,c_limit,f_auto/30f1d5f3-4c79-4a3f-9e44-0e43f2d5f3d4/sportswear-tech-fleece-joggers.png', searchQuery: 'Nike tech fleece joggers black' },
  { name: 'Aviation Cargo Pant', type: 'bottom', color: 'Cypress', material: 'Cotton Ripstop', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Carhartt WIP', price: '£119', priceValue: 119, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R03881725_CYPRESS_M?wid=800', searchQuery: 'Carhartt WIP aviation cargo pant cypress' },
  { name: 'Slim Fit Chinos', type: 'bottom', color: 'Beige', material: 'Stretch Cotton', season: 'spring', occasions: ['smart casual', 'casual'], brand: 'Polo Ralph Lauren', price: '£125', priceValue: 125, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R03984563_BEIGE_M?wid=800', searchQuery: 'Ralph Lauren slim fit chinos beige' },
  { name: 'Gale Tailored Trousers', type: 'bottom', color: 'Charcoal', material: 'Wool Blend', season: 'autumn', occasions: ['smart', 'formal'], brand: 'Reiss', price: '£148', priceValue: 148, image: '/api/proxy-image?url=https://reiss.imgix.net/media/catalog/product/1/0/10_10_2022_61_99502_CHARCOAL_FRONT.jpg?auto=format&w=800', searchQuery: 'Reiss Gale tailored trousers charcoal' },
  // SHOES
  { name: 'Air Force 1 07', type: 'shoes', color: 'White', material: 'Full Grain Leather', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Nike', price: '£109.99', priceValue: 109.99, image: '/api/proxy-image?url=https://static.nike.com/a/images/t_prod_ss/w_640,c_limit,f_auto/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoes.png', searchQuery: 'Nike Air Force 1 07 white' },
  { name: 'Yeezy Boost 350 V2', type: 'shoes', color: 'Bone', material: 'Primeknit', season: 'all', occasions: ['casual', 'streetwear'], brand: 'adidas Yeezy', price: '£220', priceValue: 220, image: '/api/proxy-image?url=https://images.stockx.com/images/adidas-Yeezy-Boost-350-V2-Bone-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90', searchQuery: 'adidas Yeezy Boost 350 V2 Bone' },
  { name: 'Chelsea Boot', type: 'shoes', color: 'Black', material: 'Italian Suede', season: 'autumn', occasions: ['smart casual', 'smart'], brand: 'Common Projects', price: '£485', priceValue: 485, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R00130556_BLACK_M?wid=800', searchQuery: 'Common Projects chelsea boot suede black' },
  { name: '550', type: 'shoes', color: 'White/Green', material: 'Leather', season: 'all', occasions: ['casual', 'streetwear'], brand: 'New Balance', price: '£110', priceValue: 110, image: '/api/proxy-image?url=https://images.stockx.com/images/New-Balance-550-White-Green-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90', searchQuery: 'New Balance 550 white green' },
  { name: 'Old Skool', type: 'shoes', color: 'Black/White', material: 'Canvas/Suede', season: 'all', occasions: ['casual'], brand: 'Vans', price: '£65', priceValue: 65, image: '/api/proxy-image?url=https://images.vans.com/is/image/Vans/D3HY28-HERO?wid=800', searchQuery: 'Vans Old Skool black white' },
  // ACCESSORIES
  { name: 'LV Initiales 40mm Belt', type: 'accessory', color: 'Monogram Brown', material: 'Coated Canvas/Leather', season: 'all', occasions: ['smart', 'smart casual'], brand: 'Louis Vuitton', price: '£450', priceValue: 450, image: '/api/proxy-image?url=https://uk.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-initiales-40mm-reversible-belt--M9151U_PM2_Front%20view.png?wid=800', searchQuery: 'Louis Vuitton LV initiales belt monogram' },
  { name: 'Submariner Date 41mm', type: 'accessory', color: 'Black/Oystersteel', material: 'Oystersteel', season: 'all', occasions: ['smart', 'formal', 'casual'], brand: 'Rolex', price: '£7,500', priceValue: 7500, image: '/api/proxy-image?url=https://content.rolex.com/dam/2024/upright-bba-with-shadow/m126610ln-0001.png?impolicy=v6-upright&imwidth=800', searchQuery: 'Rolex Submariner Date 126610LN' },
  { name: 'Aviator Classic', type: 'accessory', color: 'Gold/Green', material: 'Metal/Crystal', season: 'summer', occasions: ['casual', 'smart casual'], brand: 'Ray-Ban', price: '£159', priceValue: 159, image: '/api/proxy-image?url=https://assets.ray-ban.com/is/image/RayBan/805289602057__STD__shad__qt.png?impolicy=RB_Product&width=800', searchQuery: 'Ray-Ban aviator classic RB3025 gold green' },
  { name: 'Classic Sport Cap', type: 'accessory', color: 'Navy', material: 'Cotton Chino', season: 'all', occasions: ['casual', 'sport'], brand: 'Polo Ralph Lauren', price: '£49', priceValue: 49, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R03655102_NAVY_M?wid=800', searchQuery: 'Ralph Lauren classic sport cap navy' },
  // SMART
  { name: 'Slim Fit Oxford Shirt', type: 'top', color: 'Light Blue', material: 'Oxford Cotton', season: 'all', occasions: ['smart casual', 'smart'], brand: 'Charles Tyrwhitt', price: '£49.95', priceValue: 49.95, image: '/api/proxy-image?url=https://www.ctshirts.com/on/demandware.static/-/Sites-ctshirts-master/default/dw77a7da76/hi-res/CSR0688BLU_main_hero.jpg', searchQuery: 'Charles Tyrwhitt slim fit oxford shirt blue' },
  { name: 'Belper Polo Shirt', type: 'top', color: 'Black', material: 'Extra Fine Merino', season: 'autumn', occasions: ['smart casual', 'smart'], brand: 'John Smedley', price: '£175', priceValue: 175, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R00115124_BLACK_M?wid=800', searchQuery: 'John Smedley Belper polo shirt black' },
  { name: 'Burlington V-Neck Sweater', type: 'top', color: 'Fumo Grey', material: '100% Cashmere', season: 'winter', occasions: ['smart casual', 'smart'], brand: 'N.Peal', price: '£229', priceValue: 229, image: '/api/proxy-image?url=https://npeal.com/cdn/shop/products/NPG-221A_fumo-grey_1_800x.jpg', searchQuery: 'N.Peal Burlington cashmere v-neck fumo grey' },
  { name: 'Blanks Heavyweight Crew', type: 'top', color: 'Vintage Black', material: 'Heavyweight Cotton', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Represent', price: '£80', priceValue: 80, image: '/api/proxy-image?url=https://cdn.shopify.com/s/files/1/0181/7623/products/M05105_01_800x.jpg', searchQuery: 'Represent blanks heavyweight crew vintage black' },
  { name: 'Bulldog Swim Shorts', type: 'bottom', color: 'Navy', material: 'Quick-Dry Nylon', season: 'summer', occasions: ['casual', 'holiday'], brand: 'Orlebar Brown', price: '£175', priceValue: 175, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R03744503_NAVY_M?wid=800', searchQuery: 'Orlebar Brown Bulldog swim shorts navy' },
  { name: 'Classic Track Jacket', type: 'outerwear', color: 'Black', material: 'Technical Jersey', season: 'spring', occasions: ['casual', 'sport', 'streetwear'], brand: 'Palm Angels', price: '£395', priceValue: 395, image: '/api/proxy-image?url=https://images.selfridges.com/is/image/selfridges/R03878942_BLACK_M?wid=800', searchQuery: 'Palm Angels classic track jacket black' },
]
