export interface SeedItem {
  name: string
  type: string
  color: string
  material: string
  season: string
  occasions: string[]
  brand: string
  price: string
  priceValue: number
  image: string
  searchQuery: string
}

export const SEED_WARDROBE: SeedItem[] = [
  // TOPS
  { name: 'Paint Drip Trucker Hat', type: 'accessory', color: 'Black', material: 'Cotton/Mesh', season: 'all', occasions: ['casual', 'streetwear'], brand: 'AMIRI', price: '£295', priceValue: 295, image: 'https://cdn-images.farfetch-contents.com/17/63/76/24/17637624_37069583_1000.jpg', searchQuery: 'AMIRI paint drip trucker hat black' },
  { name: 'Compass Badge T-Shirt', type: 'top', color: 'White', material: '100% Cotton', season: 'summer', occasions: ['casual', 'streetwear'], brand: 'Stone Island', price: '£165', priceValue: 165, image: 'https://cdn-images.farfetch-contents.com/20/43/83/53/20438353_51277189_1000.jpg', searchQuery: 'Stone Island compass badge t-shirt white' },
  { name: 'Essential Fear of God Tee', type: 'top', color: 'Cream', material: '100% Cotton', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Fear of God', price: '£90', priceValue: 90, image: 'https://cdn-images.farfetch-contents.com/18/89/89/51/18898951_40998427_1000.jpg', searchQuery: 'Fear of God Essentials cream t-shirt' },
  { name: 'Polo Bear Knit Jumper', type: 'top', color: 'Navy', material: 'Cotton Blend', season: 'autumn', occasions: ['smart casual', 'casual'], brand: 'Ralph Lauren', price: '£329', priceValue: 329, image: 'https://cdn-images.farfetch-contents.com/19/27/54/23/19275423_42451789_1000.jpg', searchQuery: 'Ralph Lauren polo bear navy jumper' },
  { name: 'Classic Box Logo Tee', type: 'top', color: 'Red', material: '100% Cotton', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Supreme', price: '£148', priceValue: 148, image: 'https://images.stockx.com/images/Supreme-Box-Logo-Tee-Red.jpg', searchQuery: 'Supreme box logo tee red' },
  { name: 'Swoosh Club Fleece Hoodie', type: 'top', color: 'Black', material: 'Cotton Fleece', season: 'autumn', occasions: ['casual', 'sport'], brand: 'Nike', price: '£59.99', priceValue: 59.99, image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1d7e4c6b-07fe-4e6a-b5b0-77a6e6c7e5c9/sportswear-club-fleece-pullover-hoodie-HhMPq3.png', searchQuery: 'Nike swoosh club fleece hoodie black' },
  { name: 'Trefoil Crew Sweatshirt', type: 'top', color: 'Grey', material: 'French Terry', season: 'autumn', occasions: ['casual', 'sport'], brand: 'adidas', price: '£55', priceValue: 55, image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fd0a27cc2c724daba3b9ae8c01391064_9366/Trefoil_Crew_Sweatshirt_Grey_HE2069_01_laydown.jpg', searchQuery: 'adidas trefoil crew sweatshirt grey' },
  { name: 'Classic Harrington Jacket', type: 'outerwear', color: 'Tan', material: 'Cotton', season: 'spring', occasions: ['smart casual', 'casual'], brand: 'Baracuta', price: '£395', priceValue: 395, image: 'https://cdn-images.farfetch-contents.com/13/24/50/10/13245010_14641337_1000.jpg', searchQuery: 'Baracuta G9 harrington jacket tan' },
  { name: 'Nuptse Down Jacket', type: 'outerwear', color: 'Black', material: 'Nylon/Down', season: 'winter', occasions: ['casual', 'streetwear'], brand: 'The North Face', price: '£290', priceValue: 290, image: 'https://images.thenorthface.com/is/image/TheNorthFace/NF0A3C8D_JK3_hero', searchQuery: 'North Face 1996 nuptse jacket black' },
  { name: 'Wool Overcoat', type: 'outerwear', color: 'Camel', material: 'Wool Blend', season: 'winter', occasions: ['smart', 'formal'], brand: 'COS', price: '£175', priceValue: 175, image: 'https://image.hm.com/assets/hm/7b/a3/7ba3e4e3e9f54e34c90ba3a3b5f0c7f48e5a61c6.jpg', searchQuery: 'COS camel wool overcoat men' },
  // BOTTOMS
  { name: '501 Original Fit Jeans', type: 'bottom', color: 'Indigo', material: 'Denim', season: 'all', occasions: ['casual'], brand: "Levi's", price: '£95', priceValue: 95, image: 'https://lsco.scene7.com/is/image/lsco/005010101-front-pdp?fmt=jpeg&qlt=70&resMode=bisharp&fit=crop,0&op_usm=1.25,0.6,8&wid=2000&hei=2000', searchQuery: "Levi's 501 original fit jeans indigo" },
  { name: 'Tech Fleece Joggers', type: 'bottom', color: 'Black', material: 'Tech Fleece', season: 'all', occasions: ['casual', 'sport'], brand: 'Nike', price: '£89.99', priceValue: 89.99, image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/30f1d5f3-4c79-4a3f-9e44-0e43f2d5f3d4/sportswear-tech-fleece-joggers-ZfFbFN.png', searchQuery: 'Nike tech fleece joggers black' },
  { name: 'Cargo Utility Trousers', type: 'bottom', color: 'Olive', material: 'Cotton Twill', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Carhartt WIP', price: '£119', priceValue: 119, image: 'https://cdn-images.farfetch-contents.com/19/55/27/43/19552743_43661243_1000.jpg', searchQuery: 'Carhartt WIP cargo trousers olive' },
  { name: 'Slim Chinos', type: 'bottom', color: 'Beige', material: 'Stretch Cotton', season: 'spring', occasions: ['smart casual', 'casual'], brand: 'Polo Ralph Lauren', price: '£125', priceValue: 125, image: 'https://cdn-images.farfetch-contents.com/17/63/76/25/17637625_37069584_1000.jpg', searchQuery: 'Ralph Lauren slim chino beige' },
  { name: 'Tailored Wool Trousers', type: 'bottom', color: 'Charcoal', material: 'Wool', season: 'autumn', occasions: ['smart', 'formal'], brand: 'Reiss', price: '£148', priceValue: 148, image: 'https://reiss.imgix.net/media/catalog/product/1/0/10_10_2022_61_99502_CHARCOAL_FRONT.jpg', searchQuery: 'Reiss tailored wool trousers charcoal' },
  // SHOES
  { name: 'Air Force 1 Low', type: 'shoes', color: 'White', material: 'Leather', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Nike', price: '£109.99', priceValue: 109.99, image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoes-WrLlWX.png', searchQuery: 'Nike Air Force 1 07 white' },
  { name: 'Yeezy Boost 350 V2', type: 'shoes', color: 'Bone', material: 'Primeknit', season: 'all', occasions: ['casual', 'streetwear'], brand: 'adidas Yeezy', price: '£220', priceValue: 220, image: 'https://images.stockx.com/images/adidas-Yeezy-Boost-350-V2-Bone-Product.jpg', searchQuery: 'adidas Yeezy Boost 350 V2 Bone' },
  { name: 'Chelsea Boots', type: 'shoes', color: 'Black', material: 'Suede', season: 'autumn', occasions: ['smart casual', 'smart'], brand: 'Common Projects', price: '£485', priceValue: 485, image: 'https://cdn-images.farfetch-contents.com/12/31/39/77/12313977_11166900_1000.jpg', searchQuery: 'Common Projects chelsea boot suede black' },
  { name: 'New Balance 550', type: 'shoes', color: 'White/Green', material: 'Leather', season: 'all', occasions: ['casual', 'streetwear'], brand: 'New Balance', price: '£110', priceValue: 110, image: 'https://nb.scene7.com/is/image/NB/bb550wt1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=880&hei=880', searchQuery: 'New Balance 550 white green' },
  { name: 'Old Skool', type: 'shoes', color: 'Black/White', material: 'Canvas/Suede', season: 'all', occasions: ['casual'], brand: 'Vans', price: '£65', priceValue: 65, image: 'https://images.vans.com/is/image/Vans/D3HY28-HERO', searchQuery: 'Vans Old Skool black white' },
  // ACCESSORIES
  { name: 'Monogram Belt', type: 'accessory', color: 'Brown', material: 'Leather', season: 'all', occasions: ['smart', 'smart casual'], brand: 'Louis Vuitton', price: '£450', priceValue: 450, image: 'https://uk.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-initiales-40mm-reversible-belt-belts--M9151U_PM2_Front%20view.jpg', searchQuery: 'Louis Vuitton monogram belt' },
  { name: 'Submariner Date', type: 'accessory', color: 'Black/Silver', material: 'Oystersteel', season: 'all', occasions: ['smart', 'formal', 'casual'], brand: 'Rolex', price: '£7,500', priceValue: 7500, image: 'https://content.rolex.com/dam/2024/upright-bba-with-shadow/m126610ln-0001.png', searchQuery: 'Rolex Submariner Date black' },
  { name: 'Classic Aviator', type: 'accessory', color: 'Gold/Green', material: 'Metal', season: 'summer', occasions: ['casual', 'smart casual'], brand: 'Ray-Ban', price: '£159', priceValue: 159, image: 'https://assets.ray-ban.com/is/image/RayBan/805289602057__STD__shad__qt.png', searchQuery: 'Ray-Ban aviator classic gold green' },
  { name: 'Baseball Cap', type: 'accessory', color: 'Navy', material: 'Cotton', season: 'all', occasions: ['casual', 'sport'], brand: 'Ralph Lauren', price: '£49', priceValue: 49, image: 'https://cdn-images.farfetch-contents.com/14/79/29/03/14792903_24167553_1000.jpg', searchQuery: 'Ralph Lauren baseball cap navy' },
  // DRESS/SMART
  { name: 'Slim Fit Oxford Shirt', type: 'top', color: 'Light Blue', material: 'Oxford Cotton', season: 'all', occasions: ['smart casual', 'smart'], brand: 'Charles Tyrwhitt', price: '£49.95', priceValue: 49.95, image: 'https://www.ctshirts.com/on/demandware.static/-/Sites-ctshirts-master/default/dw77a7da76/hi-res/CSR0688BLU_main_hero.jpg', searchQuery: 'Charles Tyrwhitt slim fit oxford shirt blue' },
  { name: 'Merino Wool Polo', type: 'top', color: 'Black', material: 'Merino Wool', season: 'autumn', occasions: ['smart casual', 'smart'], brand: 'John Smedley', price: '£175', priceValue: 175, image: 'https://cdn-images.farfetch-contents.com/11/77/49/10/11774910_8589613_1000.jpg', searchQuery: 'John Smedley merino wool polo black' },
  { name: 'Cashmere V-Neck', type: 'top', color: 'Grey Marl', material: 'Cashmere', season: 'winter', occasions: ['smart casual', 'smart'], brand: 'N.Peal', price: '£229', priceValue: 229, image: 'https://cdn-images.farfetch-contents.com/12/64/35/76/12643576_12234571_1000.jpg', searchQuery: 'N.Peal cashmere v-neck grey' },
  { name: 'Heavyweight Crewneck', type: 'top', color: 'Washed Black', material: 'Heavy Cotton', season: 'all', occasions: ['casual', 'streetwear'], brand: 'Represent', price: '£80', priceValue: 80, image: 'https://cdn.shopify.com/s/files/1/0181/7623/products/M05105_01_2000x.jpg', searchQuery: 'Represent heavyweight crewneck washed black' },
  { name: 'Swim Shorts', type: 'bottom', color: 'Navy', material: 'Quick-Dry Nylon', season: 'summer', occasions: ['casual', 'holiday'], brand: 'Orlebar Brown', price: '£175', priceValue: 175, image: 'https://cdn-images.farfetch-contents.com/13/60/68/31/13606831_16023529_1000.jpg', searchQuery: 'Orlebar Brown Bulldog swim shorts navy' },
  { name: 'Logo Track Jacket', type: 'outerwear', color: 'Black', material: 'Technical Fabric', season: 'spring', occasions: ['casual', 'sport', 'streetwear'], brand: 'Palm Angels', price: '£395', priceValue: 395, image: 'https://cdn-images.farfetch-contents.com/17/12/00/71/17120071_34716559_1000.jpg', searchQuery: 'Palm Angels track jacket black' },
]
